name: github-pipeline
on: [push]
# on:
#   pull_request:
#     - main
jobs:
  checks-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0
        with:
          github-token: ${{ secrets.token }}

      - name: Download Go packages
        run: |
          go mod tidy
      - name: Pulumi Preview
        uses: pulumi/actions@v3.19.1
        with:
          command: preview
          github-token: ${{ secrets.token }}
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
          AZURE_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['clientId'] }}
          AZURE_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['clientSecret'] }}
          AZURE_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['tenantId'] }}
          ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['clientId'] }}
          ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['clientSecret'] }}
          ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['tenantId'] }}
          ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['subscriptionId'] }}
  checks-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Check my resources
        run: |
          if [ -z "$(az resource list --tag type='pulumi' | jq -r ".[].name")" ]; then
              echo "##[debug]No resources with pulumi tag on the resource group"
          else
              echo "##[debug]There are some resources on the resource group. Please consider deleting it"
          fi
      